### ISSUE TITLE
Career Support - Resumes - Build your resume

### ISSUE THREAD

**Issue by ads6495** [ads6495/assignments#30]
# Key areas of Information to include:

## Contact information
- [ ] Email
- [ ] Phone Number (Google numbers are great if you want to protect your personal number)
- [ ] Github link
- [ ] Portfolio link

## Summary
- [ ] Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” use a headline that encapsulates your credentials.

## Skills
- [ ] You’ll want to incorporate the right keywords, optimize your resume for applicant tracking systems

## Professional experience
- [ ] Focus on your accomplishments rather than your day-to-day responsibilities
Education
- [ ] Write where you went college and your degree.
- [ ] It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [ ] Volunteering and community service

## Due Date: Wednesday, September 25th
 - [ ] Upload or submit a link to your resume for review.

**Comment by ads6495** [comment]
https://www.resume.com/share/albertstrange

**Comment by ktrammell95** [comment]
Nice and clean layout, I would look at your skills area and see if you can make it columns to give you some space to see if you can fit in a project or two. You want to highlight your tech stuff as much as you can.

Also, CSS can just be CSS, most folks in the field should know what it is. Don't forget about HTML and some of the other basic things you learned.

![Screen Shot 2019-09-26 at 4 29 12 PM](https://user-images.githubusercontent.com/10440779/65722787-015d4600-e07b-11e9-8f25-a82826192143.png)

**Comment by ktrammell95** [comment]
![Screen Shot 2019-09-26 at 4 31 24 PM](https://user-images.githubusercontent.com/10440779/65722827-189c3380-e07b-11e9-9bc6-920c1da1ee52.png)


Just noticed it looks like you might have extra dots on these
